### ISSUE TITLE
[TO-DO] Hwan

### ISSUE THREAD

**Issue by hwaneest** [hwaneest/DataCamp_Donates_2021#1]
- [x] 깃헙 팀 레포 생성 
- [x] 깃헙 팀 레포 공유 / 이메일 취합
- [x] 공지사항 정리
- [x] 팀원 directory 챙기기 (총 5명)
- [x] https://meet.google.com/nnr-crma-vzp
